spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecogem
    username: ecogem
    password: eco123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: YOUR_BASE64_OR_LONG_RANDOM_SECRET_KEY_HERE